### ISSUE TITLE
Where to get Debian packages?

### ISSUE THREAD

**Issue by therealprof** [clear-code/cutter#32] opened 2017-10-04 09:17 UTC
We're a cutter user and previously we used the packages provided by Debian which recently has removed the package from it's repositories (https://tracker.debian.org/news/871063). I tried to follow the instructions on (http://cutter.sourceforge.net/reference/install-to-debian.html) but that doesn't work because `apt-get` fails to load the indices from SF:
```
Err http://downloads.sourceforge.net jessie/main amd64 Packages
Err http://downloads.sourceforge.net jessie/main amd64 Packages
Err http://downloads.sourceforge.net jessie/main amd64 Packages
Err http://downloads.sourceforge.net jessie/main amd64 Packages
Err http://downloads.sourceforge.net jessie/main amd64 Packages
Fetched 9633 kB in 28s (333 kB/s)
W: Failed to fetch http://downloads.sourceforge.net/project/cutter/debian/dists/jessie/main/binary-amd64/Packages
```

So how do I get a working cutter version now? I've already tried various modifications but without improvements.

**Comment by kenhys** [comment] 2017-10-04 13:57
Umm, I can't reproduce it...

Here is my apt-line:

```
vagrant@debian-8:~$ sudo cat /etc/apt/sources.list.d/cutter.list
deb http://downloads.sourceforge.net/project/cutter/debian/ jessie main
deb-src http://downloads.sourceforge.net/project/cutter/debian/ jessie main
```

And, I could fetch metadata from SF.

```
vagrant@debian-8:~$ sudo apt update
Hit http://security.debian.org jessie/updates InRelease
Hit http://security.debian.org jessie/updates/main Sources                                                   
Ign http://downloads.sourceforge.net jessie InRelease                                
Hit http://security.debian.org jessie/updates/main amd64 Packages                                                            
Hit http://security.debian.org jessie/updates/main Translation-en                                                            
Ign http://deb.debian.org jessie InRelease                                                                                   
Hit http://deb.debian.org jessie-updates InRelease                  
Hit http://downloads.sourceforge.net jessie Release.gpg
Hit http://deb.debian.org jessie Release.gpg                                        
Hit http://downloads.sourceforge.net jessie Release
Hit http://deb.debian.org jessie-updates/main Sources                               
Get:1 http://deb.debian.org jessie-updates/main amd64 Packages/DiffIndex [8,884 B]                   
Hit http://downloads.sourceforge.net jessie/main Sources                         
Get:2 http://deb.debian.org jessie-updates/main Translation-en/DiffIndex [3,688 B]  
Hit http://downloads.sourceforge.net jessie/main amd64 Packages                     
Hit http://deb.debian.org jessie Release                                            
Hit http://deb.debian.org jessie/main Sources                                       
Hit http://deb.debian.org jessie/main amd64 Packages              
Hit http://deb.debian.org jessie/main Translation-en                                               
Ign http://downloads.sourceforge.net jessie/main Translation-en_US                 
Ign http://downloads.sourceforge.net jessie/main Translation-en
Fetched 12.6 kB in 5s (2,124 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

What mirror site is auto selected? My nearest mirror site is jaist, but I guess your one may not not. (indices may not be correctly mirrored?)

**Comment by therealprof** [comment] 2017-10-04 14:04
I've no idea which mirror it'll pick. But my problems already started earlier because I'm using a docker container and the mirror redirects to https but the apt-transport for https is not installed by default, so I had to set that up first and then I ran into this problem.

**Comment by okkez** [comment] 2018-04-20 03:01
I've uploaded deb packages to osdn.net. We will move to osdn.net (deb/rpm package hosting) in next release.
How about following?

/etc/apt/sources.list.d/cutter.list:
```
  deb https://osdn.net/projects/cutter/storage/debian/ jessie main
  deb-src https://osdn.net/projects/cutter/storage/debian/ jessie main
```
or

/etc/apt/sources.list.d/cutter.list:
```
  deb https://osdn.net/projects/cutter/storage/debian/ stretch main
  deb-src https://osdn.net/projects/cutter/storage/debian/ stretch main
```

**Comment by kenhys** [comment] 2019-09-19 01:20
I'll close this issue.

**Closed by kenhys** 2019-09-19 01:20 UTC
